version: '3'

services:
  app:
    restart: always
    image: authserver
    build:
      context: .
      dockerfile: Dockerfile
    container_name: authserver
    working_dir: /app
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn --timeout=30 --workers=4 --worker-class gevent --bind :10080 Authserver.wsgi:application"
    networks:
      - backend


networks:
  backend:
    external: true
