# Generated by Django 2.2 on 2020-11-30 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rbac.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default=rbac.models.generate_default_nickname, max_length=256, verbose_name='昵称')),
                ('money', models.FloatField(default=0, verbose_name='余额')),
                ('member', models.BooleanField(default=False, verbose_name='会员')),
                ('viptime', models.DateTimeField(blank=True, null=True, verbose_name='会员到期时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
