# Generated by Django 2.2 on 2020-11-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hotpcount',
            field=models.IntegerField(default=0, verbose_name='HOTP_KEY_COUNT'),
        ),
    ]
